# Generated by Django 4.2.28 on 2026-03-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorapplication',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Why do you want to join this hospital?'),
        ),
    ]
